"""Curated city catalog data for city endpoints."""

from __future__ import annotations

from .types import AttractionPayload, CityPayload


def _attraction(
    name: str,
    attraction_type: str,
    duration: str,
    ticket: int,
    district: str | None = None,
    note: str | None = None,
) -> AttractionPayload:
    """Build one normalized attraction payload."""
    return {
        "name": name,
        "type": attraction_type,
        "duration": duration,
        "ticket": ticket,
        "district": district,
        "note": note,
    }


def _city(
    city_id: str,
    name: str,
    region: str,
    tags: list[str],
    budget: int,
    seasons: list[str],
    description: str,
    attractions: list[AttractionPayload],
    *,
    trip_duration: str,
    walk_intensity: str,
    rain_friendly: bool,
    family_friendly: bool,
    food_friendly: bool,
    style_label: str,
    editorial_note: str,
) -> CityPayload:
    """Build one normalized curated-city payload."""
    return {
        "id": city_id,
        "name": name,
        "region": region,
        "tags": tags,
        "avg_budget_per_day": budget,
        "best_seasons": seasons,
        "description": description,
        "attractions": attractions,
        "trip_duration": trip_duration,
        "walk_intensity": walk_intensity,
        "rain_friendly": rain_friendly,
        "family_friendly": family_friendly,
        "food_friendly": food_friendly,
        "style_label": style_label,
        "editorial_note": editorial_note,
        "data_source": "curated",
    }


def build_curated_cities() -> list[CityPayload]:
    """Return the curated city catalog used by city routes."""
    return [
        _city(
            "beijing",
            "北京",
            "华北",
            ["历史文化", "博物馆", "亲子", "城市漫步"],
            880,
            ["春季", "秋季"],
            "北京适合把世界文化遗产、顶级博物馆与胡同街区串在一起玩。第一次来通常围绕中轴线、故宫和东城街区最稳，二刷再往颐和园、国家图书馆或艺术区延伸。",
            [
                _attraction("故宫博物院", "世界文化遗产", "3-4小时", 60, "东城区", "需预约，周一闭馆"),
                _attraction("中国国家博物馆", "综合博物馆", "2-3小时", 0, "东城区", "通常需提前预约"),
                _attraction("什刹海-烟袋斜街", "城市漫步", "2小时", 0, "西城区", "适合傍晚步行和吃饭"),
            ],
            trip_duration="3-4天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="经典人文",
            editorial_note="第一次去北京，优先看中轴线和大馆，信息密度高但行程也容易控制。",
        ),
        _city(
            "shanghai",
            "上海",
            "华东",
            ["现代都市", "夜景", "美食", "购物", "亲子"],
            980,
            ["春季", "秋季"],
            "上海的优势是节奏可快可慢。想高效打卡就围绕外滩、陆家嘴、武康路和博物馆线走，想放松则把咖啡馆、街区漫步和夜景放在一个周末里也很舒服。",
            [
                _attraction("外滩", "城市地标", "1-2小时", 0, "黄浦区", "夜景体验更完整"),
                _attraction("上海博物馆东馆", "博物馆", "2-3小时", 0, "浦东新区", "热门展需要关注预约"),
                _attraction("上海迪士尼度假区", "主题乐园", "6-8小时", 475, "浦东新区", "旺季门票浮动较大"),
            ],
            trip_duration="2-3天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="都市周末",
            editorial_note="上海很适合第一次做城市型短假期，夜景、街区和馆都很集中。",
        ),
        _city(
            "hangzhou",
            "杭州",
            "华东",
            ["西湖", "自然风光", "休闲", "美食", "少走路"],
            720,
            ["春季", "秋季"],
            "杭州更像节奏放慢一点的城市假期。西湖一线、灵隐和龙井周边适合轻松安排，吃住选择成熟，适合情侣、亲子和两三天的小长假。",
            [
                _attraction("西湖", "湖景步行", "3小时", 0, "西湖区", "建议避开周末午后核心段"),
                _attraction("灵隐飞来峰景区", "人文景区", "2-3小时", 75, "西湖区", "灵隐寺香花券另计"),
                _attraction("中国茶叶博物馆双峰馆区", "专题博物馆", "1.5-2小时", 0, "西湖区", "适合和龙井村顺路安排"),
            ],
            trip_duration="2-3天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="慢节奏度假",
            editorial_note="杭州强在轻松感，不用排太满也能玩得舒服。",
        ),
        _city(
            "nanjing",
            "南京",
            "华东",
            ["历史文化", "博物馆", "梧桐大道", "城市漫步"],
            680,
            ["春季", "秋季"],
            "南京适合把民国城市气质和明代都城遗迹放在同一条线上体验。博物馆质量高，市区内景点串联效率也不错，适合历史向三日游。",
            [
                _attraction("南京博物院", "综合博物馆", "2-4小时", 0, "玄武区", "需要预约，建议上午去"),
                _attraction("明孝陵景区", "世界文化遗产", "2-3小时", 70, "玄武区", "春秋季步行体验更好"),
                _attraction("秦淮河-夫子庙片区", "城市漫步", "2小时", 0, "秦淮区", "更适合夜间散步和吃饭"),
            ],
            trip_duration="2-3天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="历史城市",
            editorial_note="南京的历史线和城市线都很清楚，适合想要内容密度但不想太累的人。",
        ),
        _city(
            "suzhou",
            "苏州",
            "华东",
            ["园林", "古城", "美食", "城市漫步", "摄影"],
            760,
            ["春季", "秋季"],
            "苏州的核心体验是园林、古城水巷和精细的城市日常。适合两天一晚的短途，也适合和上海联动，重点不在打卡数量，而在空间气质。",
            [
                _attraction("拙政园", "古典园林", "2小时", 80, "姑苏区", "旺季建议早点入园"),
                _attraction("苏州博物馆本馆", "建筑+博物馆", "1.5-2小时", 0, "姑苏区", "常需预约"),
                _attraction("平江路历史街区", "古城漫步", "1.5-2小时", 0, "姑苏区", "适合傍晚散步和小吃"),
            ],
            trip_duration="2天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="园林古城",
            editorial_note="如果你更在意审美和城市质感，苏州比纯打卡型城市更耐逛。",
        ),
        _city(
            "qingdao",
            "青岛",
            "华东",
            ["海边", "啤酒", "城市漫步", "摄影", "周末"],
            740,
            ["夏季", "秋季"],
            "青岛适合海边步行、老城区观景和轻松吃喝。老城与海岸线连接自然，节奏偏轻松，适合周末或三天两晚的海滨城市度假。",
            [
                _attraction("八大关", "城市漫步", "2小时", 0, "市南区", "秋天和工作日体验更安静"),
                _attraction("小青岛公园", "海景地标", "1小时", 10, "市南区", "适合看海和拍栈桥方向"),
                _attraction("青岛啤酒博物馆", "工业博物馆", "1.5-2小时", 60, "市北区", "适合下午安排"),
            ],
            trip_duration="2-3天",
            walk_intensity="low",
            rain_friendly=False,
            family_friendly=True,
            food_friendly=True,
            style_label="海边慢游",
            editorial_note="青岛更适合放松和步行，不是那种必须排很满的目的地。",
        ),
        _city(
            "chengdu",
            "成都",
            "西南",
            ["美食", "休闲", "熊猫", "亲子", "夜生活"],
            680,
            ["春季", "秋季"],
            "成都适合把吃喝、街区漫步和一两个重点景点放在一起。行程容错率高，下雨天也不容易完全废掉，适合第一次去西南城市的人。",
            [
                _attraction("成都大熊猫繁育研究基地", "亲子景点", "3小时", 55, "成华区", "建议尽早入园看熊猫更活跃"),
                _attraction("宽窄巷子", "城市漫步", "1.5-2小时", 0, "青羊区", "更适合感受城市氛围，不必停留太久"),
                _attraction("三星堆博物馆", "博物馆", "4小时", 72, "德阳市广汉市", "适合单独留半天安排"),
            ],
            trip_duration="3天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="松弛吃逛",
            editorial_note="成都很适合把旅行节奏放慢，重点放在吃、逛、看熊猫这种轻决策体验上。",
        ),
        _city(
            "chongqing",
            "重庆",
            "西南",
            ["山城", "夜景", "火锅", "城市漫步", "年轻人"],
            660,
            ["春季", "秋季"],
            "重庆的辨识度很强，适合喜欢立体交通、江景夜景和重口味城市氛围的人。上下坡和跨江移动较多，安排时最好按片区集中。",
            [
                _attraction("洪崖洞", "夜景地标", "1-2小时", 0, "渝中区", "更适合晚上外部观看和步行"),
                _attraction("李子坝观景平台", "城市打卡", "40分钟", 0, "渝中区", "人多时停留不用太久"),
                _attraction("长江索道", "交通体验", "1小时", 20, "渝中区/南岸区", "节假日排队时间可能较长"),
            ],
            trip_duration="2-3天",
            walk_intensity="high",
            rain_friendly=False,
            family_friendly=False,
            food_friendly=True,
            style_label="强氛围夜景",
            editorial_note="重庆适合喜欢强烈城市体验的人，但最好接受爬坡和排队。",
        ),
        _city(
            "kunming",
            "昆明",
            "西南",
            ["气候舒适", "自然风光", "博物馆", "慢节奏", "周边游"],
            620,
            ["春季", "夏季", "秋季"],
            "昆明更像云南旅行的轻松起点。城市本身节奏不赶，适合散步、看湖和做周边延展，亲子和长辈同行也相对好安排。",
            [
                _attraction("海埂大坝", "湖景步行", "1-2小时", 0, "西山区", "冬季海鸥季体验更强"),
                _attraction("云南省博物馆", "综合博物馆", "2小时", 0, "官渡区", "适合作为雨天备选"),
                _attraction("石林风景区", "自然景区", "4小时", 130, "石林彝族自治县", "更适合单独半日或一日安排"),
            ],
            trip_duration="2-3天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="轻松中转",
            editorial_note="昆明胜在舒服，不一定要排很多景点，但很适合作为西南旅行的缓冲站。",
        ),
        _city(
            "xian",
            "西安",
            "西北",
            ["历史文化", "古都", "博物馆", "美食", "亲子"],
            640,
            ["春季", "秋季"],
            "西安适合集中体验中国古代都城遗迹。兵马俑、城墙、博物馆和回坊线都很清楚，做三到四天的人文线非常成熟。",
            [
                _attraction("秦始皇帝陵博物院", "世界遗产", "4小时", 120, "临潼区", "往返市区需要预留路程"),
                _attraction("西安城墙", "古城地标", "2小时", 54, "碑林区", "骑行和傍晚登墙体验都不错"),
                _attraction("陕西历史博物馆", "综合博物馆", "2-3小时", 0, "雁塔区", "常需预约"),
            ],
            trip_duration="3-4天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="古都深度",
            editorial_note="如果你想把历史体验做扎实，西安是非常稳定的第一选择。",
        ),
        _city(
            "guangzhou",
            "广州",
            "华南",
            ["美食", "城市漫步", "亲子", "购物", "雨天友好"],
            760,
            ["秋季", "冬季"],
            "广州适合把吃和轻观光结合起来。馆和骑楼街区都成熟，雨天替代方案多，整体交通便利，家庭出行体验也比较稳。",
            [
                _attraction("陈家祠", "人文景点", "1-1.5小时", 10, "荔湾区", "适合和永庆坊连着玩"),
                _attraction("广州塔", "城市地标", "1.5-2小时", 150, "海珠区", "不同观景票型价格浮动较大"),
                _attraction("永庆坊", "街区漫步", "1.5-2小时", 0, "荔湾区", "适合傍晚顺路吃饭"),
            ],
            trip_duration="2-3天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="美食城市",
            editorial_note="广州的优势不是单个超级景点，而是整体城市可逛、可吃、可避雨。",
        ),
        _city(
            "shenzhen",
            "深圳",
            "华南",
            ["海边", "公园", "乐园", "现代都市", "周末"],
            860,
            ["秋季", "冬季"],
            "深圳更适合高效率周末游。海边、公园、商圈和主题乐园切换方便，适合不想把时间花在跨城移动上的短假期。",
            [
                _attraction("深圳湾公园", "海边步行", "1-2小时", 0, "南山区", "适合日落时段"),
                _attraction("世界之窗", "主题乐园", "4-6小时", 220, "南山区", "适合亲子或朋友同行"),
                _attraction("华侨城创意文化园", "文艺街区", "1.5-2小时", 0, "南山区", "更适合下午逛街喝咖啡"),
            ],
            trip_duration="2天",
            walk_intensity="low",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=False,
            style_label="周末轻度假",
            editorial_note="深圳很适合把周末做成不费脑的轻度假，尤其适合本地或周边城市出发。",
        ),
        _city(
            "xiamen",
            "厦门",
            "华南",
            ["海边", "文艺", "休闲", "情侣", "少走路"],
            700,
            ["春季", "秋季", "冬季"],
            "厦门适合轻松海边假期。鼓浪屿、环岛路和沙坡尾都不追求强打卡，而是适合拍照、慢慢逛和留白。",
            [
                _attraction("鼓浪屿", "海岛景点", "4小时", 35, "思明区", "岛上景点联票和船票规则需留意"),
                _attraction("环岛路", "海边骑行", "1-2小时", 0, "思明区", "适合早晨或傍晚"),
                _attraction("沙坡尾", "街区漫步", "1-2小时", 0, "思明区", "适合看店和吃饭"),
            ],
            trip_duration="2-3天",
            walk_intensity="low",
            rain_friendly=False,
            family_friendly=True,
            food_friendly=True,
            style_label="海边发呆",
            editorial_note="如果你想旅行不要太满，厦门比高密度打卡城市更舒服。",
        ),
        _city(
            "sanya",
            "三亚",
            "华南",
            ["海边", "度假", "亲子", "情侣", "高端酒店"],
            1280,
            ["冬季", "春季"],
            "三亚更适合酒店度假和海边项目结合起来玩。真正的重点常常不是把景点排满，而是把海滩、酒店和半日出海或岛上项目搭配好。",
            [
                _attraction("亚龙湾", "海滩", "2-3小时", 0, "吉阳区", "适合海边放松和度假酒店"),
                _attraction("蜈支洲岛", "海岛项目", "5小时", 144, "海棠区", "旺季排队和船班需要预留时间"),
                _attraction("太阳湾公路", "风景公路", "40分钟", 0, "吉阳区", "更适合自驾或包车顺路停靠"),
            ],
            trip_duration="3-4天",
            walk_intensity="low",
            rain_friendly=False,
            family_friendly=True,
            food_friendly=False,
            style_label="酒店度假",
            editorial_note="三亚更像松弛型度假，而不是必须不停打卡的目的地。",
        ),
        _city(
            "wuhan",
            "武汉",
            "华中",
            ["城市漫步", "博物馆", "夜景", "美食", "周末"],
            620,
            ["春季", "秋季"],
            "武汉适合做城市线和江边夜景线。高校、博物馆和老租界片区内容密度不错，美食也集中，是很稳的华中周末目的地。",
            [
                _attraction("湖北省博物馆", "博物馆", "2-3小时", 0, "武昌区", "编钟演出需单独留意场次"),
                _attraction("东湖听涛景区", "湖景步行", "2小时", 0, "武昌区", "适合慢走和骑行"),
                _attraction("黎黄陂路街头博物馆街区", "城市漫步", "1-2小时", 0, "江岸区", "适合傍晚散步"),
            ],
            trip_duration="2-3天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="江城周末",
            editorial_note="武汉不是单点爆发型城市，但整体内容密度和性价比都很稳。",
        ),
        _city(
            "changsha",
            "长沙",
            "华中",
            ["美食", "夜生活", "年轻人", "城市漫步", "周末"],
            580,
            ["春季", "秋季"],
            "长沙更适合做吃喝和夜间城市氛围体验。核心景点不算极多，但街区集中，适合年轻人或朋友同行做两天一夜的轻旅行。",
            [
                _attraction("岳麓山", "自然景区", "2-3小时", 0, "岳麓区", "可结合爱晚亭和索道安排"),
                _attraction("湖南博物院", "博物馆", "2-3小时", 0, "开福区", "常需预约"),
                _attraction("太平老街", "街区漫步", "1-2小时", 0, "天心区", "更适合和坡子街顺路安排"),
            ],
            trip_duration="2天",
            walk_intensity="medium",
            rain_friendly=True,
            family_friendly=False,
            food_friendly=True,
            style_label="夜生活美食",
            editorial_note="长沙的记忆点在城市氛围和吃喝，不一定要靠很多大景点撑满。",
        ),
        _city(
            "harbin",
            "哈尔滨",
            "东北",
            ["冰雪", "俄式风情", "冬季限定", "摄影", "亲子"],
            760,
            ["冬季"],
            "哈尔滨最强的季节性非常明确。冬天的冰雪大世界、中央大街和松花江沿线氛围很强，适合专门做一次冬季主题旅行。",
            [
                _attraction("哈尔滨冰雪大世界", "冬季乐园", "4小时", 328, "松北区", "开园时间和票价会随季节调整"),
                _attraction("中央大街", "城市漫步", "1-2小时", 0, "道里区", "夜晚氛围更好"),
                _attraction("索菲亚广场", "地标建筑", "40分钟", 0, "道里区", "适合和中央大街顺路安排"),
            ],
            trip_duration="3天",
            walk_intensity="medium",
            rain_friendly=False,
            family_friendly=True,
            food_friendly=True,
            style_label="冬季主题",
            editorial_note="如果不是冬季，哈尔滨的优势会明显下降；冬天去则非常有记忆点。",
        ),
        _city(
            "hong-kong",
            "香港",
            "港澳台",
            ["都市度假", "购物", "美食", "夜景", "亲子"],
            1380,
            ["秋季", "冬季"],
            "香港适合高密度都市体验。维港夜景、博物馆、街区和主题乐园都很成熟，但预算和步行强度通常会比内地城市更高一些。",
            [
                _attraction("维多利亚港海滨长廊", "夜景地标", "1-2小时", 0, "尖沙咀", "更适合傍晚到夜间"),
                _attraction("香港故宫文化博物馆", "专题博物馆", "2小时", 50, "西九文化区", "热门展期建议提前购票"),
                _attraction("香港迪士尼乐园", "主题乐园", "6-8小时", 639, "大屿山", "不同日期票价浮动"),
            ],
            trip_duration="3天",
            walk_intensity="high",
            rain_friendly=True,
            family_friendly=True,
            food_friendly=True,
            style_label="高密度都市",
            editorial_note="香港适合想把夜景、购物、馆和乐园浓缩进一次短假期的人。",
        ),
    ]
